// Generated by: gen
// TypeWriter: slice
// Directive: +gen on ImportSpec

package typewriter

// ImportSpecSlice is a slice of type ImportSpec. Use it where you would use []ImportSpec.
type ImportSpecSlice []ImportSpec

// SelectString projects a slice of string from ImportSpecSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv ImportSpecSlice) SelectString(fn func(ImportSpec) string) (result []string) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
