// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Tag

// See http://clipperhouse.github.io/gen for documentation

package typewriter

// TagSlice is a slice of type Tag. Use it where you would use []Tag.
type TagSlice []Tag

// Where returns a new TagSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv TagSlice) Where(fn func(Tag) bool) (result TagSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
